$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
name: ga-run-900
tags:
    modeltype: pytorch
code: ../jobs
command: >-
  python train.py 
  --data ${{inputs.data}}
inputs:
  data:
    type: uri_file
    path: azureml:WIPRO@latest # There shouldn't be space after 'azureml:'
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
  conda_file: ../config/training_env.yml
compute: azureml:computer456
display_name: stock
experiment_name: ga_train_job
description: Training job via Github actions
