name: data upload to azure

env:
  ticker: WIPRO.NS
  start: 366
  end: 1

on:
  # schedule:
  #   - cron: "1 1 * * 1"

  push:
    branches: [data-upload-automation, main] # Can't trigger on push because github actions pushes changes
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #   - .github/workflows/data_pipeline.yml
  #   - jobs/data_download.py
  #   - jobs/data_upload.yml
  #   - cli/setup.sh
permissions:
  contents: write

jobs:
  datawork:
    runs-on: self-hosted
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: 'icoder-Ahish/MLops_project'

    # - name: setup python 3.12
    #   uses: actions/setup-python@v4
    #   with: 
    #     python-version: "3.12"
    - name: setup Python venv and install packages
      run: |
        python3 -m venv .venv
        .venv/bin/python -m pip install --upgrade pip
        .venv/bin/python -m pip install -r requirements.txt

    - name: download ticker data
      run: .venv/bin/python data_download.py --ticker $ticker --start $start --end $end
      working-directory: jobs

    - name: edit yaml files
      run: .venv/bin/python update_yamls.py
      working-directory: jobs

    # - name: install python packages
    #   run: |
    #     python3 -m pip install --upgrade pip
    #     pip3 install -r requirements.txt

    # - name: download ticker data and update yml file
    #   run: python3 data_download.py --ticker $ticker --start $start --end $end
    #   id: data
    #   working-directory: jobs

    # - name: edit yaml files
    #   run: python3 update_yamls.py
    #   working-directory: jobs

    - name: push files to github
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Ticker data for $ticker downloaded and YAML file updated." || exit 0
        git push origin HEAD:${GITHUB_REF_NAME}
      # Old  git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: upload to azure
      run: az ml data create -f jobs/data_upload.yml
