name: model deployment

on:
  workflow_dispatch:
  push:
    branches: [deploy-automation, main]
    paths:
      - '.github/workflows/deployment_pipeline.yml'
      - 'jobs/deploy.yml'
      - 'jobs/deployment.py'

jobs:
  deployment-job:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: 'icoder-Ahish/MLops_project'

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Azure ML
        run: bash setup.sh
        working-directory: cli
        continue-on-error: true

      # Endpoint creation is only required during the first run.
      - name: Create endpoint
        run: az ml online-endpoint create --name ga-deployment

      - name: Deploy model
        run: az ml online-deployment update -f deploy.yml
        working-directory: jobs